#ifndef ASSOCIATOR_PRIVATE_YNP_STATION_HPP
#define ASSOCIATOR_PRIVATE_YNP_STATION_HPP
/// THIS IS AN AUTOGENERATED FILE
#include <map>
#include <utility>
#define YELLOWSTONE_SIMULATION_SIZE 400
#define YELLOWSTONE_TIME_NORMALIZATION 120.000000
namespace
{
    std::map<std::string, std::pair<double, double>> ynpStationMap{
         {"US.RLMT", std::pair<double, double> {1.24624612079396,0.18637144313936}},
         {"WY.YHB", std::pair<double, double> {0.273951270009491,0.376380570438454}},
         {"IW.LOHW", std::pair<double, double> {0.575505961172478,0.94598850824382}},
         {"WY.YHL", std::pair<double, double> {0.281017345084169,0.326348335696782}},
         {"WY.YMV", std::pair<double, double> {0.530865174570204,0.265352613550797}},
         {"WY.YTP", std::pair<double, double> {0.737026275526515,0.555849681302758}},
         {"IW.MOOW", std::pair<double, double> {0.502679509210528,0.877944180450414}},
         {"US.HLID", std::pair<double, double> {-1.39246931681589,0.941140239810194}},
         {"WY.YHR", std::pair<double, double> {0.8423561363139,0.698264461835756}},
         {"WY.YNB", std::pair<double, double> {0.519659466679263,0.38850810736594}},
         {"WY.YUF", std::pair<double, double> {0.620805182288606,0.395793691695503}},
         {"US.LKWY", std::pair<double, double> {0.677880214784012,0.469360505579608}},
         {"IW.REDW", std::pair<double, double> {0.447207405653239,1.07098671750839}},
         {"WY.MCID", std::pair<double, double> {0.278702856042091,0.656670171345819}},
         {"WY.YJC", std::pair<double, double> {0.703047838842312,0.374113985745455}},
         {"WY.YNE", std::pair<double, double> {0.874228511387709,0.247198054257054}},
         {"MB.BGMT", std::pair<double, double> {-0.148267353100166,0.13192343855379}},
         {"MB.BZMT", std::pair<double, double> {0.476710143535095,-0.0719486586785674}},
         {"MB.CRMT", std::pair<double, double> {0.805148040437325,0.0234390274238152}},
         {"MB.MOMT", std::pair<double, double> {-0.335168961529189,0.44965260213459}},
         {"MB.QLMT", std::pair<double, double> {0.155985579744854,0.33586650867698}},
         {"MB.TPMT", std::pair<double, double> {0.0359459120339607,0.385472901737818}},
         {"PB.B206", std::pair<double, double> {0.620794572170711,0.393243303856804}},
         {"PB.B207", std::pair<double, double> {0.449985301377874,0.442703394669375}},
         {"PB.B208", std::pair<double, double> {0.677133051473145,0.47186311388092}},
         {"PB.B944", std::pair<double, double> {0.60511187463071,0.557295747223946}},
         {"PB.B945", std::pair<double, double> {0.502981630493474,0.305202555855888}},
         {"PB.B950", std::pair<double, double> {0.536246594400423,0.395806384171483}},
         {"IW.PLID", std::pair<double, double> {-2.1406570605414,0.148709371943724}},
         {"WY.YLA", std::pair<double, double> {0.744844681693547,0.495394789284164}},
         {"WY.YNM", std::pair<double, double> {0.523466036321814,0.38896178558728}},
         {"IW.SNOW", std::pair<double, double> {0.497887537782295,1.02227181579943}},
         {"WY.YDD", std::pair<double, double> {0.58858765985437,0.554622472800842}},
         {"WY.YLT", std::pair<double, double> {0.582514151425218,0.533678904854744}},
         {"WY.YNR", std::pair<double, double> {0.535905271618436,0.394456381736169}},
         {"IW.TPAW", std::pair<double, double> {0.393005780420481,1.00730487114889}},
         {"WY.YEE", std::pair<double, double> {0.934150035418007,0.507990014710542}},
         {"WY.YMC", std::pair<double, double> {0.3702453667968,0.372405840634833}},
         {"WY.YPC", std::pair<double, double> {0.782932850237834,0.427543816844935}},
         {"WY.YFT", std::pair<double, double> {0.456293424051098,0.526554451018249}},
         {"WY.YML", std::pair<double, double> {0.554257089322694,0.449535632257607}},
         {"WY.YPK", std::pair<double, double> {0.919632863945342,0.384820984216262}},
         {"WY.YDC", std::pair<double, double> {0.251752908899212,0.396944786982033}},
         {"US.BOZ", std::pair<double, double> {0.0609155958241992,-0.0480024754024859}},
         {"WY.YMP", std::pair<double, double> {0.800978276738534,0.381361175227021}},
         {"WY.YPM", std::pair<double, double> {0.439783216804816,0.423606041209375}},
         {"WY.YGC", std::pair<double, double> {0.319534748171287,0.353849046857592}},
         {"IW.FLWY", std::pair<double, double> {0.525678019160534,0.710742805168955}},
         {"WY.YMR", std::pair<double, double> {0.390924175535359,0.41778502456665}},
         {"WY.YPP", std::pair<double, double> {0.472162103486986,0.616737883283306}},
         {"WY.YWB", std::pair<double, double> {0.321822115048949,0.449041587514913}},
         {"IW.IMW", std::pair<double, double> {0.400567584733636,0.805651135327719}},
         {"WY.YHH", std::pair<double, double> {0.449118313685509,0.358024490974296}},
         {"WY.YMS", std::pair<double, double> {0.613494769527887,0.620136191570238}},
         {"WY.YSB", std::pair<double, double> {0.802758240508907,0.309423221218757}},
    };
}
#endif
